export const seedProducts = [
  {
    name: "Diamond Solitaire Ring",
    slug: "diamond-solitaire-ring",
    category: "rings",
    product_type: "ready-made",
    price: 2400,
    estimated_price_from: null,
    quote_required: false,
    metal_type: "White Gold",
    gold_karat: "18K",
    gold_weight: "4.2g",
    stone_type: "Diamond",
    stone_weight: null,
    diamond_carat: "1.00 ct",
    diamond_cut: "Round Brilliant",
    diamond_color: "G",
    diamond_clarity: "VS1",
    gemstone_carat: null,
    gemstone_shape: null,
    gemstone_origin: null,
    gemstone_treatment: null,
    certificate: "Available on request",
    stock_status: "In Stock",
    short_description: "Classic 18K white gold solitaire ring with a brilliant diamond.",
    description:
      "A timeless diamond solitaire ring designed for engagement, anniversary, or luxury gifting. Final availability may depend on stock and diamond certification.",
    delivery_time: "7 to 18 business days",
    return_eligible: true,
  },
  {
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    category: "earrings",
    product_type: "ready-made",
    price: 680,
    estimated_price_from: null,
    quote_required: false,
    metal_type: "Yellow Gold",
    gold_karat: "14K",
    gold_weight: "3.1g",
    stone_type: "Pearl",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: null,
    gemstone_shape: "Drop",
    gemstone_origin: "Freshwater",
    gemstone_treatment: "Natural",
    certificate: "Available on request",
    stock_status: "In Stock",
    short_description: "Elegant pearl drop earrings with a soft luxury finish.",
    description:
      "Refined pearl earrings designed for formal occasions, bridal styling, and everyday elegance.",
    delivery_time: "7 to 18 business days",
    return_eligible: true,
  },
  {
    name: "Gold Tennis Bracelet",
    slug: "gold-tennis-bracelet",
    category: "bracelets",
    product_type: "ready-made",
    price: 1550,
    estimated_price_from: null,
    quote_required: false,
    metal_type: "Yellow Gold",
    gold_karat: "18K",
    gold_weight: "8.5g",
    stone_type: "Diamond",
    stone_weight: null,
    diamond_carat: "0.75 ct",
    diamond_cut: "Round",
    diamond_color: "H",
    diamond_clarity: "VS-SI",
    gemstone_carat: null,
    gemstone_shape: null,
    gemstone_origin: null,
    gemstone_treatment: null,
    certificate: "Available on request",
    stock_status: "In Stock",
    short_description: "Luxury gold tennis bracelet with diamond detailing.",
    description:
      "A premium bracelet for luxury styling. Price may vary for custom length, diamond grade, and gold weight.",
    delivery_time: "7 to 18 business days",
    return_eligible: true,
  },
  {
    name: "Emerald Cut Ring",
    slug: "emerald-cut-ring",
    category: "rings",
    product_type: "made-to-order",
    price: null,
    estimated_price_from: 1800,
    quote_required: true,
    metal_type: "White Gold",
    gold_karat: "18K",
    gold_weight: "Confirmed in quote",
    stone_type: "Emerald",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: "Custom",
    gemstone_shape: "Emerald Cut",
    gemstone_origin: "Available on request",
    gemstone_treatment: "Available on request",
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Made-to-order emerald cut ring with custom stone selection.",
    description:
      "This ring is created after quotation. Final price depends on emerald quality, gold rate, size, and making charges.",
    delivery_time: "2 to 8 weeks",
    return_eligible: false,
  },
  {
    name: "Diamond Pendant",
    slug: "diamond-pendant",
    category: "pendants",
    product_type: "ready-made",
    price: 980,
    estimated_price_from: null,
    quote_required: false,
    metal_type: "Rose Gold",
    gold_karat: "14K",
    gold_weight: "2.8g",
    stone_type: "Diamond",
    stone_weight: null,
    diamond_carat: "0.35 ct",
    diamond_cut: "Round",
    diamond_color: "G-H",
    diamond_clarity: "VS-SI",
    gemstone_carat: null,
    gemstone_shape: null,
    gemstone_origin: null,
    gemstone_treatment: null,
    certificate: "Available on request",
    stock_status: "In Stock",
    short_description: "Minimal diamond pendant for everyday luxury.",
    description:
      "A delicate diamond pendant crafted for refined daily wear and gifting.",
    delivery_time: "7 to 18 business days",
    return_eligible: true,
  },
  {
    name: "Custom Name Pendant",
    slug: "custom-name-pendant",
    category: "custom-jewellery",
    product_type: "custom-quote",
    price: null,
    estimated_price_from: 350,
    quote_required: true,
    metal_type: "Gold",
    gold_karat: "10K / 14K / 18K",
    gold_weight: "Confirmed in quote",
    stone_type: "Optional",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: null,
    gemstone_shape: null,
    gemstone_origin: null,
    gemstone_treatment: null,
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Personalized name pendant made according to your design.",
    description:
      "Custom name pendants are priced after confirming gold karat, name length, design thickness, chain option, and stone details.",
    delivery_time: "2 to 6 weeks",
    return_eligible: false,
  },
  {
    name: "Round Brilliant Diamond",
    slug: "round-brilliant-diamond",
    category: "gemstones",
    product_type: "gemstone",
    price: null,
    estimated_price_from: 1200,
    quote_required: true,
    metal_type: null,
    gold_karat: null,
    gold_weight: null,
    stone_type: "Diamond",
    stone_weight: null,
    diamond_carat: "1.00 ct",
    diamond_cut: "Round Brilliant",
    diamond_color: "G",
    diamond_clarity: "VS1",
    gemstone_carat: "1.00 ct",
    gemstone_shape: "Round",
    gemstone_origin: "Available on request",
    gemstone_treatment: "Certified on request",
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Round brilliant diamond available by quotation.",
    description:
      "Diamond availability and price depend on carat, cut, color, clarity, lab certification, and market rate.",
    delivery_time: "Availability confirmed in quote",
    return_eligible: false,
  },
  {
    name: "Oval Ruby Gemstone",
    slug: "oval-ruby-gemstone",
    category: "gemstones",
    product_type: "gemstone",
    price: null,
    estimated_price_from: 750,
    quote_required: true,
    metal_type: null,
    gold_karat: null,
    gold_weight: null,
    stone_type: "Ruby",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: "1.50 ct",
    gemstone_shape: "Oval",
    gemstone_origin: "Available on request",
    gemstone_treatment: "Available on request",
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Oval ruby gemstone for custom rings and pendants.",
    description:
      "Ruby price depends on color, clarity, origin, treatment, size, and certificate.",
    delivery_time: "Availability confirmed in quote",
    return_eligible: false,
  },
  {
    name: "Emerald Cut Emerald",
    slug: "emerald-cut-emerald",
    category: "gemstones",
    product_type: "gemstone",
    price: null,
    estimated_price_from: 900,
    quote_required: true,
    metal_type: null,
    gold_karat: null,
    gold_weight: null,
    stone_type: "Emerald",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: "1.25 ct",
    gemstone_shape: "Emerald Cut",
    gemstone_origin: "Available on request",
    gemstone_treatment: "Available on request",
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Emerald cut emerald for luxury custom jewellery.",
    description:
      "Emerald sourcing depends on quality, origin, treatment, carat, and current gemstone market availability.",
    delivery_time: "Availability confirmed in quote",
    return_eligible: false,
  },
  {
    name: "Blue Sapphire Oval Stone",
    slug: "blue-sapphire-oval-stone",
    category: "gemstones",
    product_type: "gemstone",
    price: null,
    estimated_price_from: 850,
    quote_required: true,
    metal_type: null,
    gold_karat: null,
    gold_weight: null,
    stone_type: "Sapphire",
    stone_weight: null,
    diamond_carat: null,
    diamond_cut: null,
    diamond_color: null,
    diamond_clarity: null,
    gemstone_carat: "1.40 ct",
    gemstone_shape: "Oval",
    gemstone_origin: "Available on request",
    gemstone_treatment: "Available on request",
    certificate: "Available on request",
    stock_status: "Request Quote",
    short_description: "Blue sapphire oval stone for rings and bridal jewellery.",
    description:
      "Sapphire quote depends on color depth, origin, treatment, size, and certificate.",
    delivery_time: "Availability confirmed in quote",
    return_eligible: false,
  },
];